"""Added indexes

Revision ID: 479841e119f
Revises: 34c4a3c687b
Create Date: 2015-12-01 16:21:32.634476

"""

# revision identifiers, used by Alembic.
revision = '479841e119f'
down_revision = '34c4a3c687b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('pl1e_parent_idx', 'publishleveloneentity', ['parent_client_id', 'parent_object_id'], unique=False)
    op.create_index('pl1e_entity_type_idx', 'publishleveloneentity', ['entity_type'], unique=False)
    op.create_index('pl1e_entity_idx', 'publishleveloneentity', ['entity_client_id', 'entity_object_id'], unique=False)
    op.create_index('pl1e_deleted_idx', 'publishleveloneentity', ['marked_for_deletion'], unique=False)
    op.create_index('l1e_parent_idx', 'leveloneentity', ['parent_client_id', 'parent_object_id'], unique=False)
    op.create_index('l1e_entity_type_idx', 'leveloneentity', ['entity_type'], unique=False)
    op.create_index('l1e_deleted_idx', 'leveloneentity', ['marked_for_deletion'], unique=False)
    op.create_index('l1e_content_idx', 'leveloneentity', ['content'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('l1e_content_idx', table_name='leveloneentity')
    op.drop_index('l1e_deleted_idx', table_name='leveloneentity')
    op.drop_index('l1e_entity_type_idx', table_name='leveloneentity')
    op.drop_index('l1e_parent_idx', table_name='leveloneentity')
    op.drop_index('pl1e_deleted_idx', table_name='publishleveloneentity')
    op.drop_index('pl1e_entity_idx', table_name='publishleveloneentity')
    op.drop_index('pl1e_entity_type_idx', table_name='publishleveloneentity')
    op.drop_index('pl1e_parent_idx', table_name='publishleveloneentity')
    ### end Alembic commands ###
