"""Model Fixes

Revision ID: 4ef639cacf7e
Revises: 943015aa70cb
Create Date: 2017-01-26 15:57:05.476007

"""

# revision identifiers, used by Alembic.
revision = '4ef639cacf7e'
down_revision = '943015aa70cb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE dictionaryperspectivetofield DROP CONSTRAINT IF EXISTS dictionaryperspectivetofield_link_client_id_fkey")
    op.execute("ALTER TABLE entity DROP CONSTRAINT IF EXISTS entity_link_client_id_fkey")
    # try:
    #     op.drop_constraint('dictionaryperspectivetofield_link_client_id_fkey', 'dictionaryperspectivetofield', type_='foreignkey')
    # except ProgrammingError:
    #     pass
    # op.drop_constraint('entity_link_client_id_fkey', 'entity', type_='foreignkey')
    op.alter_column('lexicalentry', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('objecttoc', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('objecttoc', 'table_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objecttoc', 'table_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('objecttoc', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lexicalentry', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key('entity_link_client_id_fkey', 'entity', 'lexicalentry', ['link_client_id', 'link_object_id'], ['client_id', 'object_id'])
    op.create_foreign_key('dictionaryperspectivetofield_link_client_id_fkey', 'dictionaryperspectivetofield', 'dictionaryperspective', ['link_client_id', 'link_object_id'], ['client_id', 'object_id'])
    # ### end Alembic commands ###
