"""Grants

Revision ID: b939aa2120fa
Revises: 4ef639cacf7e
Create Date: 2017-04-17 13:56:29.413683

"""

# revision identifiers, used by Alembic.
revision = 'b939aa2120fa'
down_revision = '4ef639cacf7e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Text, String
from sqlalchemy.dialects import postgresql
from lingvodoc.models import SLBigInteger, EpochType

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrequest',
    sa.Column('id', SLBigInteger(), nullable=False),
    sa.Column('sender_id', SLBigInteger(), nullable=False),
    sa.Column('recipient_id', SLBigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('broadcast_uuid', sa.String(36), nullable=False),
    sa.Column('type', sa.String(1000), nullable=False),
    sa.Column('message', sa.String(1000), nullable=True),
    sa.Column('subject', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant',
    sa.Column('id', SLBigInteger(), nullable=False),
    sa.Column('translation_gist_client_id', SLBigInteger(), nullable=False),
    sa.Column('translation_gist_object_id', SLBigInteger(), nullable=False),
    sa.Column('issuer_translation_gist_client_id', SLBigInteger(), nullable=False),
    sa.Column('issuer_translation_gist_object_id', SLBigInteger(), nullable=False),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('issuer_url', sa.String(2048), nullable=False),
    sa.Column('grant_url', sa.String(2048), nullable=False),
    sa.Column('grant_number', sa.String(1000), nullable=False),
    sa.Column('owners', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('additional_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['translation_gist_object_id', 'translation_gist_client_id'], ['translationgist.object_id', 'translationgist.client_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('userblobs', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userblobs', 'marked_for_deletion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('grant')
    op.drop_table('userrequest')
    # ### end Alembic commands ###
